development:
  secret_key_base: AIzaSyCdkqynS4DcbA4IIQ5ckQtWleJtkReb7hk
  google_client_id: 58588679975-ska4i0tjgcq83d0soukkf13s9uas0ii9.apps.googleusercontent.com
  google_client_secret: 15VJogddHBVz8FE8PqmpbzrQ

  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

